import json
import os

from models import RemediationPR, DriftAnalysis, FileChange, Violation

# Dry-run response used when --dry-run flag is set or Bedrock is unavailable
_DRY_RUN_RESPONSE = RemediationPR(
    title="🛡️ Guardrail remediation: payments-svc (3 violations)",
    body=(
        "## Guardrail Remediation: payments-svc\n\n"
        "**Violations found:** 3\n\n"
        "### Likely Cause\n"
        "Tags (`env`, `cost-centre`, `service`) were removed during a Terraform refactor "
        "(likely a recent `terraform fmt` or module restructure). "
        "Base image `python:3.10-slim` was pinned in the Dockerfile and not updated "
        "when the golden path moved to v1.5 (`python:3.12-slim`).\n\n"
        "### Remediation\n"
        "- `terraform/tags.tf` — added missing `env`, `cost-centre`, `service` tags\n"
        "- `Dockerfile` — updated base image from `python:3.10-slim` to `python:3.12-slim`\n\n"
        "### Risk\n"
        "**Medium** — tag additions and image updates are non-destructive. "
        "Review the Terraform plan before merging to confirm no resource replacement.\n\n"
        "---\n"
        "*Auto-generated by the Agent-in-the-Loop enforcement agent. "
        "Human approval required before merge.*"
    ),
    analyses=[
        DriftAnalysis(
            resource_id="payments-svc",
            violations=[
                Violation(resource="payments-svc", violation="missing_tags", severity="medium", detail="Missing: cost-centre, env, service"),
                Violation(resource="payments-svc", violation="outdated_base_image", severity="high", detail="python:3.10-slim → python:3.12-slim"),
                Violation(resource="payments-svc", violation="iam_too_broad", severity="high", detail="s3:* on resource *"),
            ],
            likely_cause="Tags removed during Terraform refactor. Base image pinned to old version.",
            remediation_summary="Add missing tags, update base image, scope IAM policy.",
        )
    ],
    files_changed=[
        FileChange(path="terraform/tags.tf", description="Added missing env, cost-centre, service tags"),
        FileChange(path="Dockerfile", description="Updated python:3.10-slim → python:3.12-slim"),
    ],
    risk_level="medium",
    requires_human_approval=True,
)


def reason(violations: list[dict], state: dict, dry_run: bool = False) -> RemediationPR:
    """Reason over violations using Amazon Bedrock, or return dry-run response."""
    if dry_run or not violations:
        if not violations:
            return None
        return _DRY_RUN_RESPONSE

    return _call_bedrock(violations, state)


def _call_bedrock(violations: list[dict], state: dict) -> RemediationPR:
    """Call Amazon Bedrock via Anthropic SDK + Instructor for structured reasoning."""
    import anthropic
    import instructor

    region = os.environ.get("AWS_DEFAULT_REGION", "ap-southeast-2")
    model_id = os.environ.get("BEDROCK_MODEL_ID", "au.anthropic.claude-sonnet-4-6")

    bedrock_client = anthropic.AnthropicBedrock(aws_region=region)
    client = instructor.from_anthropic(bedrock_client)

    prompt = (
        "You are a platform engineering agent. Analyse these OPA policy violations "
        "and generate a remediation pull request.\n\n"
        f"Violations:\n{json.dumps(violations, indent=2)}\n\n"
        f"Deployed state context:\n{json.dumps(state, indent=2)}\n\n"
        "For each violation:\n"
        "- Determine the likely cause of drift\n"
        "- Generate the specific file change to remediate\n"
        "- Assess risk level (low/medium/high)\n"
        "- Set requires_human_approval=true always\n\n"
        "Output a single PR that fixes all violations."
    )

    return client.messages.create(
        model=model_id,
        response_model=RemediationPR,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=4096,
    )
