import json
import os

from models import RemediationPR, DriftAnalysis, FileChange, Violation

# Dry-run response used when --dry-run flag is set or Bedrock is unavailable
_DRY_RUN_RESPONSE = RemediationPR(
    title="🛡️ Guardrail remediation: payments-svc (5 violations)",
    body=(
        "## Guardrail Remediation: payments-svc\n\n"
        "**Violations found:** 5\n\n"
        "### Likely Cause\n"
        "Service was bootstrapped before current platform guardrails were enforced. "
        "Tags were partially set, base image was pinned to an old version, "
        "IAM policy uses wildcards, and a secret is stored as a plain environment variable.\n\n"
        "### Remediation\n"
        "- `config/tags.yaml` — added missing `env`, `cost-centre`, `service` tags\n"
        "- `Dockerfile` — updated base image from `python:3.10-slim` to `python:3.12-slim`\n"
        "- `config/iam-policy.json` — scoped IAM actions from `s3:*` to least-privilege\n"
        "- `config/secrets.yaml` — migrated DB_PASSWORD to secrets manager reference\n\n"
        "### Risk\n"
        "**Medium** — tag additions and image updates are non-destructive. "
        "IAM and secret changes require careful review.\n\n"
        "---\n"
        "*Auto-generated by the Agent-in-the-Loop enforcement agent. "
        "Human approval required before merge.*"
    ),
    analyses=[
        DriftAnalysis(
            resource_id="payments-svc",
            violations=[
                Violation(resource="payments-svc", violation="missing_tags", severity="medium", detail="Missing: cost-centre, env, service"),
                Violation(resource="payments-svc", violation="outdated_base_image", severity="high", detail="python:3.10-slim → python:3.12-slim"),
                Violation(resource="payments-svc", violation="iam_too_broad", severity="high", detail="s3:* on resource *"),
                Violation(resource="payments-svc", violation="iam_resource_wildcard", severity="high", detail="Wildcard resource *"),
                Violation(resource="payments-svc", violation="secret_not_managed", severity="medium", detail="DB_PASSWORD stored as env_var"),
            ],
            likely_cause="Service bootstrapped before current guardrails. Never hardened post-deployment.",
            remediation_summary="Add missing tags, update base image, scope IAM, migrate secret.",
        )
    ],
    files_changed=[
        FileChange(path="config/tags.yaml", description="Added missing env, cost-centre, service tags"),
        FileChange(path="Dockerfile", description="Updated python:3.10-slim → python:3.12-slim"),
        FileChange(path="config/iam-policy.json", description="Scoped s3:* to least-privilege actions"),
        FileChange(path="config/secrets.yaml", description="Migrated DB_PASSWORD to secrets manager reference"),
    ],
    risk_level="medium",
    requires_human_approval=True,
)


def reason(violations: list[dict], state: dict, dry_run: bool = False) -> RemediationPR:
    """Reason over violations using Amazon Bedrock, or return dry-run response."""
    if dry_run or not violations:
        if not violations:
            return None
        return _DRY_RUN_RESPONSE

    return _call_bedrock(violations, state)


def _call_bedrock(violations: list[dict], state: dict) -> RemediationPR:
    """Call Amazon Bedrock via Anthropic SDK + Instructor for structured reasoning."""
    import anthropic
    import instructor

    region = os.environ.get("AWS_DEFAULT_REGION", "ap-southeast-2")
    model_id = os.environ.get("BEDROCK_MODEL_ID", "au.anthropic.claude-sonnet-4-6")

    bedrock_client = anthropic.AnthropicBedrock(aws_region=region)
    client = instructor.from_anthropic(bedrock_client)

    prompt = (
        "You are a platform engineering agent. Analyse these OPA policy violations "
        "and generate a remediation pull request.\n\n"
        f"Violations:\n{json.dumps(violations, indent=2)}\n\n"
        f"Deployed state context:\n{json.dumps(state, indent=2)}\n\n"
        "IMPORTANT RULES:\n"
        "- Do NOT reference specific infrastructure tools (Terraform, ECS, Kubernetes) unless they appear in the violations.\n"
        "- Keep file paths generic: use 'config/tags.yaml', 'Dockerfile', 'config/iam-policy.json', 'config/secrets.yaml'.\n"
        "- Keep the likely_cause concise — 1-2 sentences maximum.\n"
        "- Keep each FileChange description to one line.\n"
        "- Set requires_human_approval=true always.\n\n"
        "For each violation:\n"
        "- Determine the likely cause of drift (concise)\n"
        "- Generate the specific file change to remediate\n"
        "- Assess risk level (low/medium/high)\n\n"
        "Output a single PR that fixes all violations."
    )

    try:
        return client.messages.create(
            model=model_id,
            response_model=RemediationPR,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=4096,
        )
    except Exception as e:
        print(f"  ⚠️  Bedrock call failed: {e}")
        print("  ℹ️  Falling back to dry-run response. Re-run with --dry-run to suppress this warning.")
        return _DRY_RUN_RESPONSE
